export const items = [
  {
    name: "Збір id 1",
    organization: "Організація 1",
    img: "",
    current_donations: 1000,
    max_donations: 10000,
    donaters: 1024,
    complete: true,
  },
  {
    name: "Збір id 2",
    organization: "Організація 2",
    img: "",
    current_donations: 2500,
    max_donations: 20000,
    donaters: 500,
    complete: false,
  },
  {
    name: "Збір id 3",
    organization: "Організація 3",
    img: "",
    current_donations: 1500,
    max_donations: 15000,
    donaters: 300,
    complete: true,
  },
  {
    name: "Збір id 4",
    organization: "Організація 1",
    img: "",
    current_donations: 8000,
    max_donations: 10000,
    donaters: 900,
    complete: false,
  },
  {
    name: "Збір id 5",
    organization: "Організація 2",
    img: "",
    current_donations: 6000,
    max_donations: 12000,
    donaters: 700,
    complete: true,
  },
];
